apiVersion: v1
kind: Pod
metadata:
  name: api1
  labels:
    app: api
spec:
  containers:
  - name: api
    image: sonnm/expressjs
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
      - containerPort: 1337
    resources:
      requests:
        memory: "256Mi"
        cpu: "0.5"
      limits:
        memory: "512Mi"
        cpu: "1"

---
apiVersion: v1
kind: Pod
metadata:
  name: api2
  labels:
    app: api
spec:
  containers:
  - name: api
    image: sonnm/expressjs
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
      - containerPort: 1337
    resources:
      requests:
        memory: "256Mi"
        cpu: "0.5"
      limits:
        memory: "512Mi"
        cpu: "1"