apiVersion: v1
kind: Pod
metadata:
  name: api1
  labels:
    app: api
spec:
  containers:
  - name: api
    image: sonnm/express-todo
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: DB_URI
      value: "mysql://root:123456@mysql-service:3306/k8s"
    ports:
      - containerPort: 1337
    resources:
      requests:
        memory: "256Mi"
        cpu: "0.5"
      limits:
        memory: "512Mi"
        cpu: "1"

---